/**
 * Central RBAC — add roles/permissions here; routes use requirePermission().
 * Do not scatter role string checks across handlers.
 *
 * Roles (internal keys stay stable in DB):
 * - ceo — full access + admin
 * - manager — team visibility / performance (view-mostly; no BD day-to-day ops)
 * - telesales — BD (create leads, notes, status, send email)
 */

export const ROLES = ['ceo', 'manager', 'telesales'];

/** Display names for UI (DB still stores ceo / manager / telesales). */
export const ROLE_LABELS = {
  ceo: 'CEO',
  manager: 'Manager',
  telesales: 'BD',
};

export function roleLabel(role) {
  return ROLE_LABELS[role] || role || '—';
}

export const PERMISSIONS = {
  // Analytics
  'analytics:view_all': ['ceo'],
  'analytics:view_team': ['ceo', 'manager'],
  'analytics:view_own': ['ceo', 'manager', 'telesales'],

  // Leads — manager can view/assign team leads but not edit BD work
  'leads:view_all': ['ceo', 'manager'],
  'leads:view_own': ['ceo', 'manager', 'telesales'],
  'leads:create': ['ceo', 'telesales'],
  'leads:update_any': ['ceo'],
  'leads:update_own': ['ceo', 'telesales'],
  'leads:import': ['ceo', 'telesales'],
  'leads:assign': ['ceo', 'manager'],
  'leads:delete': ['ceo'],

  // Follow-ups — manager view-only
  'followups:view_all': ['ceo', 'manager'],
  'followups:view_own': ['ceo', 'manager', 'telesales'],
  'followups:manage_own': ['ceo', 'telesales'],
  'followups:manage_team': ['ceo'],

  // Working tree
  'working_tree:view_all': ['ceo'],
  'working_tree:view_team': ['ceo', 'manager'],
  'working_tree:view_own': ['ceo', 'manager', 'telesales'],

  // Admin / employees
  'admin:employees': ['ceo'],
  'admin:settings': ['ceo'],

  // Revenue logging
  'revenue:record': ['ceo'],
  'revenue:view': ['ceo', 'manager'],

  // Cold email (Brevo) — BD + CEO only; manager watches replies/performance
  'email:bulk_send': ['ceo', 'telesales'],
};

export function roleHasPermission(role, permission) {
  const allowed = PERMISSIONS[permission];
  if (!allowed) return false;
  return allowed.includes(role);
}

export function canAccessLead(user, lead) {
  if (!lead) return false;
  if (roleHasPermission(user.role, 'leads:view_all')) return true;
  return lead.assigned_to === user.id || lead.created_by === user.id;
}

export const LEAD_SOURCES = {
  signup_no_listing: {
    key: 'signup_no_listing',
    label: 'Signed up · no purchase',
    description: 'Registered on BMGenie — has not bought a package yet',
  },
  free_credit_no_purchase: {
    key: 'free_credit_no_purchase',
    label: 'Free credit · no purchase',
    description: 'Used free trial credit but never bought a package',
  },
  purchased_no_repurchase: {
    key: 'purchased_no_repurchase',
    label: 'Credits used · no repurchase',
    description: 'Bought a package, used all credits, has not repurchased',
  },
  checkout_abandoned: {
    key: 'checkout_abandoned',
    label: 'Stripe · abandoned checkout',
    description: 'Opened Stripe payment box on BMGenie but did not complete payment',
  },
  revision_requested: {
    key: 'revision_requested',
    label: 'Asked for revisions',
    description: 'Requested listing revisions on BMGenie',
  },
  demo_booking: {
    key: 'demo_booking',
    label: 'Book a demo',
    description: 'Booked a demo via Calendly on bmgenie.ai',
  },
  chat_support: {
    key: 'chat_support',
    label: 'Chat support',
    description: 'Started a Tawk.to chat on bmgenie.ai',
  },
  csv_import: {
    key: 'csv_import',
    label: 'CSV / Google Sheet',
    description: 'Imported from CSV or Google Sheet export',
  },
  telesales: {
    key: 'telesales',
    label: 'BD',
    description: 'Generated by BD in CRM',
  },
  manual: {
    key: 'manual',
    label: 'Manual',
    description: 'Created manually by staff',
  },
};

/**
 * Conversion funnel — unique leads, one current stage each.
 * Activities (emails, LinkedIn, calls) are counted separately.
 */
export const LEAD_STATUSES = [
  'uncontacted',
  'contacted',
  'engaged',
  'qualified',
  'demo_scheduled',
  'challenge_offered',
  'challenge_accepted',
  'trial',
  'paid',
  'repeat',
  'nurture',
];

/** Map legacy / previous funnel labels → current stages. */
export const LEGACY_STATUS_MAP = {
  // Previous CRM funnel
  conversation: 'engaged',
  demo_booked: 'demo_scheduled',
  lost: 'nurture',
  // Older dispositions
  new: 'uncontacted',
  interested: 'engaged',
  neutral: 'engaged',
  follow_up_scheduled: 'contacted',
  not_interested: 'nurture',
  converted: 'paid',
  // Email-style labels (UI filters)
  not_contacted: 'uncontacted',
  email_sent: 'contacted',
  replied: 'engaged',
  bounced: 'nurture',
};

export const STATUS_LABELS = {
  uncontacted: 'New / Uncontacted',
  contacted: 'Contacted',
  engaged: 'Engaged / Replied',
  qualified: 'Qualified',
  demo_scheduled: 'Demo scheduled',
  challenge_offered: 'Shoot Challenge offered',
  challenge_accepted: 'Shoot Challenge accepted',
  trial: 'Test completed',
  paid: 'Paid customer',
  repeat: 'Repeat / expanded',
  nurture: 'Nurture / Disqualified',
  // legacy display
  conversation: 'Engaged / Replied',
  demo_booked: 'Demo scheduled',
  lost: 'Nurture / Disqualified',
  new: 'New / Uncontacted',
  interested: 'Engaged / Replied',
  converted: 'Paid customer',
};

/** Sidebar status tabs → URL slug under /leads/:filter */
export const LEAD_STATUS_TABS = [
  { slug: 'uncontacted', status: 'uncontacted', label: 'Uncontacted' },
  { slug: 'contacted', status: 'contacted', label: 'Contacted' },
  { slug: 'engaged', status: 'engaged', label: 'Engaged' },
  { slug: 'qualified', status: 'qualified', label: 'Qualified' },
  { slug: 'demo-scheduled', status: 'demo_scheduled', label: 'Demo scheduled' },
  { slug: 'challenge-offered', status: 'challenge_offered', label: 'Challenge offered' },
  { slug: 'challenge-accepted', status: 'challenge_accepted', label: 'Challenge accepted' },
  { slug: 'trial', status: 'trial', label: 'Test completed' },
  { slug: 'paid', status: 'paid', label: 'Paid' },
  { slug: 'repeat', status: 'repeat', label: 'Repeat' },
  { slug: 'nurture', status: 'nurture', label: 'Nurture / DQ' },
];

/** Legacy URL slugs still resolve via resolveLeadFilter. */
export const LEGACY_STATUS_TABS = [
  { slug: 'conversation', status: 'engaged', label: 'Engaged' },
  { slug: 'demo-booked', status: 'demo_scheduled', label: 'Demo scheduled' },
  { slug: 'lost', status: 'nurture', label: 'Nurture / DQ' },
];

export const LOST_REASONS = [
  'No response',
  'Not interested',
  'Budget / price',
  'Competitor',
  'Timing / not ready',
  'Wrong fit',
  'Unqualified',
  'Other',
];

/** Activity types — counts as work done, not unique funnel opportunities. */
export const ACTIVITY_TYPES = [
  'call',
  'call_attempted',
  'call_connected',
  'email',
  'email_sent',
  'email_followup',
  'linkedin',
  'linkedin_connection_sent',
  'linkedin_connection_accepted',
  'linkedin_message',
  'linkedin_reply',
  'linkedin_followup',
  'meeting_scheduled',
  'reply',
  'demo_shown',
  'note',
  'whatsapp',
];

export const LINKEDIN_ACTIVITY_TYPES = [
  'linkedin_connection_sent',
  'linkedin_connection_accepted',
  'linkedin_message',
  'linkedin_reply',
  'linkedin_followup',
  'meeting_scheduled',
];

export const REPLY_OUTCOMES = ['positive', 'negative', 'neutral', 'no_reply'];

/** Product segment tabs (auto-created from bmgenie.ai). */
export const PRODUCT_LEAD_TABS = [
  { slug: 'signup', source: 'signup_no_listing', label: 'Signup · no purchase' },
  { slug: 'free-credit', source: 'free_credit_no_purchase', label: 'Free credit · no purchase' },
  { slug: 'winback', source: 'purchased_no_repurchase', label: 'Win-back · no repurchase' },
  { slug: 'checkout-abandoned', source: 'checkout_abandoned', label: 'Stripe · abandoned' },
  { slug: 'revisions', source: 'revision_requested', label: 'Asked for revisions' },
];

export const OPEN_STATUSES = [
  'uncontacted',
  'contacted',
  'engaged',
  'qualified',
  'demo_scheduled',
  'challenge_offered',
  'challenge_accepted',
  'trial',
];

export const END_STATUSES = ['paid', 'repeat', 'nurture'];

/** Stages that should stop automated email sequences. */
export const STOP_OUTREACH_STATUSES = [
  'engaged',
  'qualified',
  'demo_scheduled',
  'challenge_offered',
  'challenge_accepted',
  'trial',
  'paid',
  'repeat',
  'nurture',
];

export function normalizeStatus(status) {
  if (!status) return status;
  if (LEAD_STATUSES.includes(status)) return status;
  return LEGACY_STATUS_MAP[status] || status;
}

export function statusLabel(status) {
  const key = normalizeStatus(status);
  return STATUS_LABELS[key] || String(status || '').replace(/_/g, ' ');
}

export function resolveLeadFilter(slug) {
  if (!slug) return {};
  const statusTab =
    LEAD_STATUS_TABS.find((t) => t.slug === slug) ||
    LEGACY_STATUS_TABS.find((t) => t.slug === slug);
  if (statusTab) {
    if (statusTab.statuses) return { statuses: statusTab.statuses };
    return { status: statusTab.status };
  }
  const productTab = PRODUCT_LEAD_TABS.find((t) => t.slug === slug);
  if (productTab) return { source: productTab.source };
  return {};
}
