/**
 * Central RBAC — add roles/permissions here; routes use requirePermission().
 * Do not scatter role string checks across handlers.
 */

export const ROLES = ['ceo', 'manager', 'telesales'];

export const PERMISSIONS = {
  // Analytics
  'analytics:view_all': ['ceo'],
  'analytics:view_team': ['ceo', 'manager'],
  'analytics:view_own': ['ceo', 'manager', 'telesales'],

  // Leads
  'leads:view_all': ['ceo', 'manager'],
  'leads:view_own': ['ceo', 'manager', 'telesales'],
  'leads:create': ['ceo', 'manager', 'telesales'],
  'leads:update_any': ['ceo', 'manager'],
  'leads:update_own': ['ceo', 'manager', 'telesales'],
  'leads:import': ['ceo', 'manager'],
  'leads:assign': ['ceo', 'manager'],

  // Follow-ups
  'followups:view_all': ['ceo', 'manager'],
  'followups:view_own': ['ceo', 'manager', 'telesales'],
  'followups:manage_own': ['ceo', 'manager', 'telesales'],
  'followups:manage_team': ['ceo', 'manager'],

  // Working tree
  'working_tree:view_all': ['ceo'],
  'working_tree:view_team': ['ceo', 'manager'],
  'working_tree:view_own': ['ceo', 'manager', 'telesales'],

  // Admin / employees
  'admin:employees': ['ceo'],
  'admin:settings': ['ceo'],

  // Revenue logging
  'revenue:record': ['ceo', 'manager'],
  'revenue:view': ['ceo', 'manager'],
};

export function roleHasPermission(role, permission) {
  const allowed = PERMISSIONS[permission];
  if (!allowed) return false;
  return allowed.includes(role);
}

export function canAccessLead(user, lead) {
  if (!lead) return false;
  if (roleHasPermission(user.role, 'leads:view_all')) return true;
  return lead.assigned_to === user.id || lead.created_by === user.id;
}

export const LEAD_SOURCES = {
  signup_no_listing: {
    key: 'signup_no_listing',
    label: 'Signed up · no purchase',
    description: 'Registered on BMGenie — has not bought a package yet',
  },
  free_credit_no_purchase: {
    key: 'free_credit_no_purchase',
    label: 'Free credit · no purchase',
    description: 'Used free trial credit but never bought a package',
  },
  purchased_no_repurchase: {
    key: 'purchased_no_repurchase',
    label: 'Credits used · no repurchase',
    description: 'Bought a package, used all credits, has not repurchased',
  },
  csv_import: {
    key: 'csv_import',
    label: 'CSV / Google Sheet',
    description: 'Imported from CSV or Google Sheet export',
  },
  telesales: {
    key: 'telesales',
    label: 'Telesales',
    description: 'Generated by telesales in CRM',
  },
  manual: {
    key: 'manual',
    label: 'Manual',
    description: 'Created manually by staff',
  },
};

/**
 * Sales funnel stages (queues).
 * Outreach (email / LinkedIn / call / reply) is logged as activities; rates live on Funnel dashboard.
 */
export const LEAD_STATUSES = [
  'qualified',
  'conversation',
  'demo_booked',
  'trial',
  'paid',
  'lost',
];

/** Map legacy disposition statuses → funnel stages (read + one-time migrate). */
export const LEGACY_STATUS_MAP = {
  new: 'qualified',
  contacted: 'qualified',
  interested: 'conversation',
  neutral: 'conversation',
  follow_up_scheduled: 'conversation',
  not_interested: 'lost',
  converted: 'paid',
};

export const STATUS_LABELS = {
  qualified: 'Qualified',
  conversation: 'Conversation',
  demo_booked: 'Demo booked',
  trial: 'Trial',
  paid: 'Paid',
  lost: 'Lost',
  // legacy labels (pre-migration reads)
  new: 'Qualified',
  contacted: 'Qualified',
  interested: 'Conversation',
  neutral: 'Conversation',
  follow_up_scheduled: 'Conversation',
  not_interested: 'Lost',
  converted: 'Paid',
};

/** Sidebar status tabs → URL slug under /leads/:filter */
export const LEAD_STATUS_TABS = [
  { slug: 'qualified', status: 'qualified', label: 'Qualified' },
  { slug: 'conversation', status: 'conversation', label: 'Conversation' },
  { slug: 'demo-booked', status: 'demo_booked', label: 'Demo booked' },
  { slug: 'trial', status: 'trial', label: 'Trial' },
  { slug: 'paid', status: 'paid', label: 'Paid' },
  { slug: 'lost', status: 'lost', label: 'Lost' },
];

export const LOST_REASONS = [
  'No response',
  'Not interested',
  'Budget / price',
  'Competitor',
  'Timing / not ready',
  'Wrong fit',
  'Unqualified',
  'Other',
];

export const ACTIVITY_TYPES = [
  'call',
  'email',
  'linkedin',
  'reply',
  'demo_shown',
  'note',
  'whatsapp',
];

export const REPLY_OUTCOMES = ['positive', 'negative', 'neutral', 'no_reply'];

/** Product segment tabs (auto-created from bmgenie.ai). */
export const PRODUCT_LEAD_TABS = [
  { slug: 'signup', source: 'signup_no_listing', label: 'Signup · no purchase' },
  { slug: 'free-credit', source: 'free_credit_no_purchase', label: 'Free credit · no purchase' },
  { slug: 'winback', source: 'purchased_no_repurchase', label: 'Win-back · no repurchase' },
];

export const OPEN_STATUSES = ['qualified', 'conversation', 'demo_booked', 'trial'];
export const END_STATUSES = ['paid', 'lost'];

export function normalizeStatus(status) {
  if (!status) return status;
  return LEGACY_STATUS_MAP[status] || status;
}

export function statusLabel(status) {
  const key = normalizeStatus(status);
  return STATUS_LABELS[key] || String(status || '').replace(/_/g, ' ');
}

export function resolveLeadFilter(slug) {
  if (!slug) return {};
  const statusTab = LEAD_STATUS_TABS.find((t) => t.slug === slug);
  if (statusTab) {
    if (statusTab.statuses) return { statuses: statusTab.statuses };
    return { status: statusTab.status };
  }
  const productTab = PRODUCT_LEAD_TABS.find((t) => t.slug === slug);
  if (productTab) return { source: productTab.source };
  return {};
}
